// frontend/src/components/Header.jsx
function Header(){
    return(
        

            <header>
        <img src="/images/postorbit-black.png" alt="postorbit" />
        <nav>
            <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Contact</a></li>
            <li><a href="">About</a></li>
            <li><a href="">Services</a></li>
            </ul>
        </nav>
        <button className="btn">login</button>
    </header>

        
    )
}

export default Header

// frontend/src/lib/Header.svelte
<script>
  import logo from "../assets/postorbit.png";
</script>

<header>
  <img src={logo} alt="postorbit" />
  <nav>
    <ul>
      <li><a href="#">Home</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Services</a></li>
    </ul>
  </nav>
  <button class="btn">login</button>
</header>
